src/homeoffice/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('calendar/', views.CalendarView.as_view(), name='calendar'),
  path('mycal/', views.MyCalendarView.as_view(), name='mycal'),
  path('timesheet/', views.TimeSheetView.as_view(), name='timesheet'),
  path('montage/', views.MontageCalendarView.as_view(), name='montage'),
  path('montage/add_service/', views.ServiceAddView.as_view(), name='add_service'),
  path('montage/delete_service/<int:id>/', views.service_delete_view, name='delete_service'),
  path('montage/edit_service/<int:id>/', views.ServiceEditView.as_view(), name='edit_service'),
  path('montage/add_task/', views.TaskAddView.as_view(), name='add_task'),
    path('montage/add_date_task/<int:day>/<int:month>/<int:year>/<str:place>/', views.TaskDateAddView.as_view(), name='add_date_task'),
  path('montage/delete_task/<int:id>/', views.task_delete_view, name='delete_task'),
  path('montage/edit_task/<int:id>/', views.TaskEditView.as_view(), name='edit_task'),
  path('montage/mycal_montage/', views.MyMontageCalendarView.as_view(), name='mycal_montage'),
  path('default_time/', views. DefaultTimeView.as_view(), name='default_time'),
  path('<int:id>/delete_time/', views.default_time_delete, name='default_time_delete'),
  path('<int:id>/view/', views.detailed_event_view, name='event_view'),
  path('<int:id>/delete/', views. event_delete_view, name='event_delete'),
  path('<int:id>/edit/', views.DetailedEditView.as_view(), name='event_edit'),
  path('add_event/<str:event_type>/', views.AddEventView.as_view(), name='add_event'),
  path('add_time/<str:line_type>/<int:timesheet>/', views.AddTimeView.as_view(), name='add_time'),
#  path("accounts/", include("django.contrib.auth.urls")),
]

src/meldungen/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path("reg/", include("reg.urls")),
  path("homeoffice/", include("homeoffice.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/reg/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
  # Working with multiple issues

  # list issues - redirects to a list with the same issue_type
  path("<slug:issue_type>/list/", views.IssueList.as_view(), name="issue_list"),

  # Working with 1 issue

  # add issue - redirects to menu
  path("<slug:issue_type>/add/", views.AddIssue.as_view(), name="issue_add"), 
  # detailed issue - redirects to the same view (issue detailed view) 
  path("satisfied/", views.satisfied_view, name="satisfied"), 
  path("<int:id>/view/", views.ViewDetailedIssue.as_view(), name="issue_detailed"),
  # update issue - redirects to a list with the same issue_type
  path("<int:id>/update/", views.UpdateIssue.as_view(), name="issue_update"),
  # change issue status - redirects to a list with the same issue_type
  path("<int:id>/change_status/", views.issue_status_change_view, name="issue_status_change"),
  
  # Delete operations

  # redirects to a list with the same issue_type
  path("<int:id>/delete/", views.issue_delete_view, name="issue_delete"),
  path("<int:pic_id>/<int:issue_id>/delete_pic/", views.issue_delete_pic_view, name="issue_delete_pic"),
  path("<int:comment_id>/<int:issue_id>/delete_comment/", views.issue_delete_comment_view, name="issue_delete_comment"),

  # General

  # redirects to menu if authorized
  path("", views.index, name="index"),
  path("menu/", views.menu, name="menu"),
  path("accounts/", include("django.contrib.auth.urls")),
  ]

src/homeoffice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class EmployeeAbsenceGroup(models.Model):
  name = models.CharField(max_length=120, verbose_name="Name")
  description = models.TextField(max_length=500, verbose_name="Description")

  def __str__(self):
    return self.name

class AbsenceType(models.Model):
  name = models.CharField(max_length=120, verbose_name="Name")
  description = models.TextField(max_length=500, verbose_name="Description")
  color = models.CharField(max_length=30, verbose_name="Farbe")
  working_time = models.BooleanField(default=False)

  def __str__(self):
    return self.name

class EmployeeGroup(models.Model):
  name = models.CharField(max_length=120, verbose_name="Name")
  description = models.TextField(max_length=500, verbose_name="Description")

  def __str__(self):
    return self.name

class Employee(models.Model):
  user_link = models.OneToOneField(
    User,
    on_delete=models.PROTECT,
    primary_key=True,
    )
  # user_link = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_linked', verbose_name="User")
  employee_group_link = models.ForeignKey(EmployeeGroup, on_delete=models.PROTECT, related_name='users_group', verbose_name="User group")
  employee_absence_group_link = models.ForeignKey(EmployeeAbsenceGroup, on_delete=models.PROTECT, related_name='absence_group', verbose_name="User absence group", blank=True, null=True)
  default_time_category_is_office = models.BooleanField(verbose_name="Default time category is office", default=True, blank=True, null=False) # otherwise workshop

  def __str__(self):
    return f"{self.user_link.first_name} {self.user_link.last_name}"
    # return str(self.user_link.first_name) + " " str(self.user_link.last_name)

class Project(models.Model):
  number = models.CharField(max_length=120, verbose_name="Number", blank=True, null=False)
  description = models.TextField(max_length=500, verbose_name="Description", blank=True, null=False)
  status = models.BooleanField(verbose_name="Active", default=True, blank=True, null=False)

  def __str__(self):
    return self.number

class Place(models.Model):
  project = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name="Project place", null=False, blank=False)
  name = models.CharField(max_length=120, verbose_name="Name", blank=True, null=False)

  def __str__(self):
    return f"{self.project.number} {self.name}"

class Vehicle(models.Model):
  name = models.CharField(max_length=120, verbose_name="Name", blank=True, null=False)
  number = models.CharField(max_length=120, verbose_name="Number", blank=True, null=False)
  employee = models.ForeignKey(Employee, on_delete=models.PROTECT, verbose_name="Employee's default car", null=True, blank=True)

  def __str__(self):
    if self.employee:
      return f"{self.name} ({self.employee.user_link.first_name} {self.employee.user_link.last_name})"
    else:
      return f"{self.name}"

class Task(models.Model):
  start_date = models.DateField(verbose_name="Anfangsdatum", null=False, blank=False)
  end_date = models.DateField(verbose_name="Datum des Endes", null=False, blank=False)
  employee_link = models.ForeignKey(Employee, on_delete=models.PROTECT, related_name='workers_task', verbose_name="Worker", null=False, blank=False)
  vehicle = models.ForeignKey(Vehicle, on_delete=models.PROTECT, related_name='vehicle_task', verbose_name="Vehicle", null=True, blank=True)
  place = models.ForeignKey(Place, on_delete=models.PROTECT, related_name='place_task', verbose_name="Task place", null=False, blank=False)

  def __str__(self):
    return f"{self.start_date} -- {self.end_date} {self.employee_link} {self.place}"

class Service(models.Model):
  start_date = models.DateField(verbose_name="Anfangsdatum", null=False, blank=False)
  end_date = models.DateField(verbose_name="Datum des Endes", null=False, blank=False)
  vehicle_link = models.ForeignKey(Vehicle, on_delete=models.PROTECT, related_name='vehicle_service', verbose_name='Vehicle', null=False, blank=False)

  def __str__(self):
    return f"{self.start_date} -- {self.end_date} {self.vehicle_link}"

class MontageSetup(models.Model):
  montage_group = models.ForeignKey(EmployeeGroup, on_delete=models.PROTECT, verbose_name="Montage group", related_name="default_montage_group", null=True)

class WorkTimeBase(models.Model):
  WEEKDAYS = {
    "1": "Mo",
    "2": "Di",
    "3": "Mi",
    "4": "Do",
    "5": "Fr",
    "6": "Sa",
    "7": "So"
  }
  employee = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="User", null=False, blank=False)
  weekday = models.CharField(max_length=4, choices=WEEKDAYS, verbose_name="Weekday", null=False, blank=False)
  start_time=models.TimeField(null=True, blank=False)
  end_time=models.TimeField(null=True, blank=False)

  class Meta:
    abstract=True
  
  def __str__(self):
    return f"{self.employee} {self.weekday}"

class WorkTimeSetup(WorkTimeBase):
  pass

class DefaultWorkTime(WorkTimeBase):
  working_time=models.DecimalField(null=True, max_digits=4, decimal_places=1)
  break_time=models.DecimalField(null=True, max_digits=4, decimal_places=1)

class TimeSheet(models.Model):
  STATUSES = {
    'created': 'Erstellt',
    'sent': 'Gesendet',
    'approved': 'Genehmigt',
    'rejected': 'Abgelehnt'
  }
  employee=models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="User", null=False, blank=False)
  year=models.IntegerField(null=False)
  month=models.IntegerField(null=False)
  status=models.CharField(max_length=10, choices=STATUSES, default='created', verbose_name='Event status')

  def __str__(self):
    return f"{self.employee} {self.year} {self.month} {self.status}" 

class TimeSheetLine(models.Model):
  ts=models.ForeignKey(TimeSheet, on_delete=models.PROTECT, verbose_name="Time Sheet", null=False, blank=False)
  day=models.IntegerField(null=False)
  start_time=models.TimeField(null=True, blank=False)
  end_time=models.TimeField(null=True, blank=False)
  working_time=models.DecimalField(null=True, max_digits=4, decimal_places=1)
  break_time=models.DecimalField(null=True, max_digits=4, decimal_places=1)

  def __str__(self):
    return f"{self.ts} {self.day}" 

class TimeSheetProjectLine(models.Model):
  ts=models.ForeignKey(TimeSheet, on_delete=models.PROTECT, verbose_name="Time Sheet", null=False, blank=False)
  day=models.IntegerField(null=False)
  project=models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name="Project", null=False, blank=False)
  working_time=models.DecimalField(null=True, max_digits=4, decimal_places=1)
  def __str__(self):
    return f"{self.ts} {self.day} {self.project}" 

class TimeSheetSetup(models.Model):
  holiday_setup = models.ForeignKey(AbsenceType, on_delete=models.PROTECT, verbose_name="Holiday setup", related_name="holiday_setups", null=True)
  study_setup = models.ForeignKey(AbsenceType, on_delete=models.PROTECT, verbose_name="Study setup", related_name="study_setups", null=True)
  illness_setup = models.ForeignKey(AbsenceType, on_delete=models.PROTECT, verbose_name="Illness setup", related_name="illness_setups", null=True)

class AbsenceEvent(models.Model):
  """ We have a blank calendar, so we put all the events into this table:
  - absence of an employee or an employee group (EmployeeAbsenceGroup)
  - holidays
  - when employee wants to work on holidays or weekends
  Then we sum up everything and display a month with all the info about the day
  """
  class Meta:
    permissions = [
      ("change_own", "Can change only own events"),
      ("change_all", "Can change all events"),
     ]
  DAY_TYPES = {
    "full": "1",
    "half": "1/2",
    "quarter": "1/4"
  }
  EVENT_TYPES = {
    "holiday": "Holiday",
    "employee_event": "Employee",
    "employee_group_event": "Employee group"
  }
  start_date = models.DateField(verbose_name="Start date")
  end_date = models.DateField(verbose_name="End date")
  employee_link = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_link', verbose_name="User", null=True)
  absence_type = models.ForeignKey(AbsenceType, on_delete=models.PROTECT, related_name='absence_type_event', verbose_name="Absence type", null=True)
  # to be able to add absence by the group and not by employee
  employee_absence_group_link = models.ForeignKey(EmployeeAbsenceGroup, on_delete=models.PROTECT, related_name='EAG_date', verbose_name="Employee absence group", null=True)
  event_type = models.CharField(max_length=20, choices=EVENT_TYPES, default="employee_event", verbose_name="Type of event")
  day_type = models.CharField(max_length=20, choices=DAY_TYPES, default="full", verbose_name="Type of the day")
  comment = models.CharField(max_length=220, verbose_name="Comment", blank=True)
  created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_created', verbose_name="Created by")
  created = models.DateTimeField(auto_now_add=True, verbose_name="Created at")

  def __str__(self):
    absence_name = ""
    match self.event_type:
      case "employee_event":
        absence_name += str(self.employee_link) + " " + str(self.absence_type)
      case "employee_group_event":
        absence_name += str(self.employee_absence_group_link) + " Gruppe" + " " + str(self.absence_type)
      case "holiday":
        absence_name += "Holiday"
    absence_name += " " + str(self.start_date) + "-" + str(self.end_date)
    return absence_name

src/homeoffice/templates/homeoffice/add_event.html
{% extends "homeoffice/base.html" %}
  {% block title %}{{ pagename }}{% endblock %}
{% block content %}
<h1>{{ pagename }}</h1>
  <form method="post" enctype="multipart/form-data" class="pure-form pure-form-stacked" action="{% if add %}{% url 'add_event' event_type %}">{% else %}{% url 'event_edit' id %}">{% endif %}
  <fieldset>
    {% csrf_token %}
    {{ form }}
    <button type="submit" value="Einreichen" class="pure-button pure-button-primary">Save</button>
  </fieldset>
</form>
{% if event_type != 'holiday' %}
{% include 'homeoffice/legend.html' %}
{% endif %}
{% endblock %}

src/homeoffice/templates/homeoffice/add_service.html
{% extends "homeoffice/base.html" %}
  {% block title %}{{ pagename }}{% endblock %}
  {% block content %}
<h1>{{ pagename }}</h1>
<form method="post" class="pure-form pure-form-stacked" action="{% if id %}{% url posturl id %}{% else %}{% url posturl %}{% endif %}">
  <fieldset>
    {% csrf_token %}
    {{ form }}
    <button type="submit" value="Einreichen" class="pure-button pure-button-primary">Save</button>
  </fieldset>
</form>
{% endblock %}

src/homeoffice/templates/homeoffice/add_time.html
{% extends "homeoffice/base.html" %}
  {% block title %}{{ pagename }}{% endblock %}
  {% block content %}
<h1>{{ pagename }}</h1>
<ul>
  <li>Employee: {{ employee }}</li>
  <li>Year: {{ year }}</li>
  <li>Month: {{ month }}</li>
</ul>
<form method="post" enctype="multipart/form-data" class="pure-form pure-form-stacked" action="{% url 'add_time' line_type timesheet %}">
  <fieldset>
    {% csrf_token %}
    {{ form }}
    <button type="submit" value="Einreichen" class="pure-button pure-button-primary">Save</button>
  </fieldset>
</form>
{% endblock %}

src/homeoffice/templates/homeoffice/base.html
<!DOCTYPE html>
<html lang="de">
  <head>
    {% block head %}
    {% load static %}
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'homeoffice/css/grids-responsive-min.css' %}">
    <link rel="stylesheet" href="{% static 'homeoffice/css/pure-min.css' %}">
    <link rel="stylesheet" href="{% static 'homeoffice/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}" >
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>{% block title %}{% endblock %} - Homeoffice</title>
    {% endblock %}
  </head>
  <body>
    <div> 
      <div class="header">
        <div class="pure-menu pure-menu-horizontal">
          <a class="pure-menu-heading" href="{% url 'calendar' %}">Homeoffice</a>
          <ul class="pure-menu-list">
            <li class="pure-menu-item pure-menu-selected">
              <a href="{% url 'calendar' %}" class="pure-menu-link"><span class="material-symbols-outlined">home</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="pure-menu-item" ><a href="/reg" class="pure-menu-link"><span class="material-symbols-outlined">add_comment</span></a></li>
            <li class="pure-menu-item"><a href="{% url 'mycal' %}" class="pure-menu-link"><span class="material-symbols-outlined">person</span></a></li>
            <li class="pure-menu-item"><a href="{% url 'timesheet' %}" class="pure-menu-link"><span class="material-symbols-outlined">punch_clock</span></a></li>
            <li class="pure-menu-item"><a href="{% url 'default_time' %}" class="pure-menu-link"><span class="material-symbols-outlined">tune</span></a></li>
            <li class="pure-menu-item"><a href="{% url 'montage' %}" class="pure-menu-link"><span class="material-symbols-outlined">engineering</span></a></li>
            <li class="pure-menu-item"><a href="{% url 'mycal_montage' %}" class="pure-menu-link"><span class="material-symbols-outlined">event_upcoming</span></a></li>
            
            <li class="pure-menu-item">
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button class="pure-button" type="submit"><span class="material-symbols-outlined">logout</span></button>
              </form>
            </li>
            {% else %}
            <li class="pure-menu-item">
              <a href="{% url 'login' %}" class="pure-menu-link"><span class="material-symbols-outlined">login</span></a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
      <div class="content pure-u-1">
        {% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert {{ message.tags }}"{% endif %}>
          <span class="closebtn">&times;</span>
          {{ message }}</div>
        {% endfor %}
        <script>
        var acc = document.getElementsByClassName("closebtn");
        var i;

        for (i = 0; i < acc.length; i++) {
        acc[i].onclick = function(){
        var div = this.parentElement;
        div.style.opacity = "0";
        setTimeout(function(){ div.style.display = "none"; }, 600);
        }
        }
        </script>
        {% endif %}
        {% block content %}{% endblock %}</div>
      <div class="footer">
        {% block footer %}&copy; Copyright 2024 by {% endblock %}
      </div>
    </div>
  </body>
</html>

src/homeoffice/templates/homeoffice/cell_bg.html
style="background-color:{% for color in e_colors %}{% if forloop.parentloop.counter0 == forloop.counter0 %}{{color.color}}{% endif %}{% endfor %}"

src/homeoffice/templates/homeoffice/default_time.html
{% extends "homeoffice/base.html" %}
  {% block title %}Standard working hours{% endblock %}
  {% block content %}
  <h1>Standard working hours</h1>
  <p>Employee: {{ e_full_name}}</p>
  <p>Absence group for the employee: {{ e_abs_group }}</p>
  <p>Employee group: {{ e_group }}</p>
  <table class="pure-table pure-table-bordered">
    <thead>
      <tr>
        <th>Day</th>
        <th>Working time, period</th>
        <th>Pause, minutes</th>
        <th>Working hours</th>
      </tr>
    </thead>
    <tbody>{% for day in day_dict_arr %}
      <tr>
        <td>{{ day.day }}</td>
        <td>{% for start, finish, link in day.times_for_tpl %}{{ start }} &ndash; {{ finish }} <a href="{{ link }}">[x]</a><br>{% endfor %}</td>
        <td>{% if day.pause != 0 %}{{ day.pause }}{% endif %}</td>
        <td>{% if day.working_time != 0 %}{{ day.working_time }}{% endif %}</td>
      </tr>{% endfor %}
      <tr>
        <td>In total</td>
        <td></td>
        <td></td>
        <td>{% if working_time_week != 0 %}{{ working_time_week }}{% endif %}</td>
      </tr>
    </tbody>
  </table>
<h2>Add time</h2>
  <p>Please add time in the format: hh:mm.</p>
  <form method="post" class="pure-form pure-form-stacked" action="{% url 'default_time' %}">
    <fieldset>
      {% csrf_token %}
      {{ form }}
      <button type="submit" value="filter" class="pure-button pure-button-primary">Save</button>
    </fieldset>
  </form>
  {% endblock %}

src/homeoffice/templates/homeoffice/event_view.html
{% extends "homeoffice/base.html" %}
  {% block title %}Detailed event view{% endblock %}
  {% block content %}
  <h1>Detailed event </h1>
  <ul>
    {% if employee %}
    <li>Employee: {{ employee }}</li>
    {% elif eag %}
    <li>Employee group: {{ eag }}</li>
    {% else %}
    <li>Holiday</li>
    {% endif %}
    {% if absence_type %}
    <li>Absence type: {{ absence_type }} ({{ absence_descr }})</li>
    {% endif %}
    <li>Period: ab {{ event.start_date }} bis {{ event.end_date}}</li>
    <li>Day type: {{ event.get_day_type_display }}</li>
    <li>Comment: {{ event.comment }}</li>
    <li>Author: {{ created_by }}</li>
    <li>Created: {{ event.created }}</li>
  </ul>{% if perms.homeoffice.change_own and user == employee %}
  <div class="pure-menu pure-menu-horizontal">
    <ul class="pure-menu-list">
      <li class="pure-menu-item pure-menu-selected"><a href="{% url 'event_edit' id %}" class="pure-menu-link"><span class="material-symbols-outlined">edit</span></a></li> 
      <li class="pure-menu-item pure-menu-selected"><a href="{% url 'event_delete' id %}" class="pure-menu-link"><span class="material-symbols-outlined">delete</span></a></li>
    </ul>
  </div>{% elif perms.homeoffice.change_all %}
  <div class="pure-menu pure-menu-horizontal">
    <ul class="pure-menu-list">
      <li class="pure-menu-item pure-menu-selected"><a href="{% url 'event_edit' id %}" class="pure-menu-link"><span class="material-symbols-outlined">edit</span></a></li> 
      <li class="pure-menu-item pure-menu-selected"><a href="{% url 'event_delete' id %}" class="pure-menu-link"><span class="material-symbols-outlined">delete</span></a></li>
    </ul>
  </div>{% endif %}
  {% endblock %}

src/homeoffice/templates/homeoffice/fractions.html
<a href="{{ event.link }}" title="{{ event.comment }}">{% if event.day_type == 'half' %}&frac12;{% elif event.day_type == 'quarter' %}&frac14;{% endif %}{{ event.text }}</a>

src/homeoffice/templates/homeoffice/montage.html
{% extends "homeoffice/base.html" %}
  {% block title %}Assembly calendar{% endblock %}
  {% block content %}
  <h1>Calendar for {{ month }}.{{ year }}</h1>
  <form method="post" class="pure-form" action="{% url 'montage' %}">
    {% csrf_token %}
    <fieldset>
      {{ form.year_switch.label_tag }}
      {{ form.year_switch }}
      {{ form.month_switch.label_tag }}
      {{ form.month_switch }}
      <button type="submit" value="filter" class="pure-button pure-button-primary">Go</button>{% if perms.homeoffice.change_task %}
      <a href="{% url 'add_task' %}" class="pure-button pure-button-primary"><span class="material-symbols-outlined">task_alt</span> Add a task</a>
      <a href="{% url 'add_service' %}" class="pure-button pure-button-primary"><span class="material-symbols-outlined">construction</span> Add a service</a>{% endif %}
    </fieldset>
  </form>
  <table class="pure-table-bordered pure-table">
    <thead>
      <tr>
        <th>CW</th>
        {% for week_number in week_numbers %}<th style="text-align: center" colspan="{{ week_number.colspan }}">{{ week_number.week_number }}</th>{% endfor %}
      </tr>
      <tr>
        <th>Day</th>
        {% for day in monthweekday %}<th>{{ day }}</th>{% endfor %}
      </tr>
      <tr>
        <th>Project \ Day</th>{% for day in monthday %}
        <th{% if today_day == day %} id="today"{% endif %}>{{ day }}</th>{% endfor %}
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Holidays</strong></td>{% for day in monthday %}
        <td{% for weekend in weekends %}{% if day == weekend.day %} style="background-color: {{ weekend.color }}"{% endif %}{% endfor %}>{% for event in holidays %}{% if day == event.day %}<p style="text-align:center">{% spaceless %}{% include 'homeoffice/fractions.html' %}{% endspaceless %}</p>{% endif %}{% endfor %}</td>{% endfor %}
        </tr>{% for place in places %}
      <tr>
        <td>{{ place }}</td>{% for day in monthday %}
        <td{% for weekend in weekends %}{% if day == weekend.day %} style="background-color: {{ weekend.color }}"{% endif %}{% endfor %}><ul>{% for task in tasks %}{% if task.day == day and task.place == place.id %}<li><span style="color:#2980b9">{{ task.car }}</span>/{{ task.worker }}{% if perms.homeoffice.change_task %} <a href="{% url 'delete_task' task.id %}">[x]</a>&nbsp;<a href="{% url 'edit_task' task.id %}">[b]</a>{% endif %}</li>{% endif %}{% endfor %}</ul>{% if perms.homeoffice.change_task %}<p style="text-align:center"><a href="{% url 'add_date_task' day month year place.id %}"><span class="material-symbols-outlined">add_circle</span></a></p>{% endif %}</td>{% endfor %}
      </tr>{% endfor %}

      <tr>
        <td><strong>Free assemblers</strong></td>{% for day in monthday %}
        <td{% for weekend in weekends %}{% if day == weekend.day %} style="background-color: {{ weekend.color }}"{% endif %}{% endfor %}><ul>{% for e_day, e_list in employees %}{% if day == e_day %}{% for e_fn, e_ln in e_list %}<li>{{ e_fn }} {{ e_ln}}</li>{% endfor %}{% endif %}{% endfor %}</ul></td>{% endfor %}
      </tr>
      <tr>
        <td><strong>Free cars</strong></td>{% for day in monthday %}
        <td{% for weekend in weekends %}{% if day == weekend.day %} style="background-color: {{ weekend.color }}"{% endif %}{% endfor %}><ul>{% for car_day, car_list in free_cars %}{% if day == car_day %}{% for car in car_list %}<li>{{ car }}</li>{% endfor %}{% endif %}{% endfor %}</ul></td>{% endfor %}
      </tr>
      <tr>
        <td><strong>Absent assemblers</strong></td>{% for day in monthday %}
        <td{% for weekend in weekends %}{% if day == weekend.day %} style="background-color: {{ weekend.color }}"{% endif %}{% endfor %}><ul>{% for a_day, a_list in absence_list %}{% if day == a_day %}{% for absence in a_list %}<li>{{ absence }}</li>{% endfor %}{% endif %}{% endfor %}</ul></td>{% endfor %}
      </tr>
      <tr>
        <td><strong>Cars in service</strong></td>{% for day in monthday %}
        <td{% for weekend in weekends %}{% if day == weekend.day %} style="background-color: {{ weekend.color }}"{% endif %}{% endfor %}><ul>{% for service in service_list %}{% if day == service.day %}<li>{{ service.car }}{% if perms.homeoffice.change_task %} <a href="{% url 'delete_service' service.id %}">[x]</a>&nbsp;<a href="{% url 'edit_service' service.id %}">[b]</a>{% endif %}</li>{% endif %}{% endfor %}</ul></td>{% endfor %}
      </tr>
    </tbody>
  </table>
  {% endblock %}